name: cece0719 the shop
version: 1.2.1
slug: wallpad
description: 테스트
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
map:
  - share:rw
url: https://github.com/cece0719/ha-addon
ports:
  8001/tcp: 8001
startup: application
boot: auto
uart: true
options:
#  type: serial
  logging:
    mqtt: true
    serial: true
#  serial:
#    port: "/dev/ttyUSB0"
#  socket:
#    port: 8899
#  mqtt:
#    server: 192.168.x.x
#    receiveDelay: 10000
schema:
#  type: list(serial|socket)
  logging:
    mqtt: bool
    serial: bool
#  serial:
#    port: str?
#  socket:
#    port: int?
#  mqtt:
#    server: str
#    receiveDelay: int